# Generated by Django 3.2.7 on 2021-09-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolo',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doce',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
            ],
        ),
    ]
