# Generated by Django 3.2.7 on 2021-10-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolo',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='doce',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
