# Generated by Django 3.2.7 on 2021-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20211030_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
