# Generated by Django 3.2.7 on 2021-10-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0004_alter_bolo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.FileField(blank=True, upload_to=('C:\\Users\\Rodrigo\\Documents\\Rodrigo\\UNIVESP\\PI\\UNIVESP-PI1-DoceSonho\\frontend/static/upload/',)),
        ),
        migrations.AlterField(
            model_name='doce',
            name='foto',
            field=models.FileField(blank=True, upload_to=('C:\\Users\\Rodrigo\\Documents\\Rodrigo\\UNIVESP\\PI\\UNIVESP-PI1-DoceSonho\\frontend/static/upload/',)),
        ),
    ]
