# Generated by Django 3.2.7 on 2021-10-31 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0005_auto_20211030_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.FileField(blank=True, max_length=5000, upload_to=('C:\\Users\\Rodrigo\\Documents\\Rodrigo\\UNIVESP\\PI\\UNIVESP-PI1-DoceSonho\\frontend/static/upload/',)),
        ),
    ]
