# Generated by Django 3.2.7 on 2021-10-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0006_alter_bolo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.FileField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='doce',
            name='foto',
            field=models.FileField(blank=True, upload_to='upload'),
        ),
    ]
