# Generated by Django 3.2.7 on 2021-10-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20211031_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='doce',
            name='foto',
            field=models.FileField(blank=True, upload_to='upload/'),
        ),
    ]
