# Generated by Django 4.0.4 on 2022-05-04 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classificacao', '0001_initial'),
        ('Portfolio', '0009_auto_20211108_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quitute',
            new_name='Produtos',
        ),
        migrations.DeleteModel(
            name='Bolo',
        ),
        migrations.DeleteModel(
            name='Doce',
        ),
    ]
