# Generated by Django 4.0.4 on 2022-05-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0010_rename_quitute_produtos_delete_bolo_delete_doce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='identificador',
            new_name='ID',
        ),
    ]
