# Generated by Django 4.0.5 on 2022-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0011_rename_identificador_produtos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
